### ISSUE TITLE
JWTAuthentication Project : Token never expires

### ISSUE THREAD

**Issue by sh-erfan** [jignesht24/Aspnetcore#2]
Since this example is what I was looking for, I noticed that token never expires. I changed expire claim to 1 minute from now, but there is no effect. I used fiddler, postman and also a console app...
Is there something tricky that I don't realize here??

**Comment by jignesht24** [comment]
Yes, I also realize this. when I set expire time 1 min, token is not expire in 1 min. But it will expire in few min.
In my case it will expire after 4 min. Please try, is the same behavior at your end?

**Comment by sh-erfan** [comment]
> Yes, I also realize this. when I set expire time 1 min, token is not expire in 1 min. But it will expire in few min.
> In my case it will expire after 4 min. Please try, is the same behavior at your end?

Yes. You are right. It expires after about 4 or 5 mins. Although  4 minutes don't matter in most scenarios, But it is very important when your server needs to have strict control over your clients' activity.
I also checked this by setting expires to 10 minutes from now, and it expired after 14 minutes. It seems that 4 minutes of delay in expiring token is default behavior here and this delay fault (is this really a fault?) is same (about 4 minutes) for all expire times we set. 
Anyhow, Thanks for your notice. You can close this issue if you prefer.
But the WHY is still with me... :-)
